### ISSUE TITLE
Add Sign Up and Log In page

### ISSUE THREAD

**Issue by sayanp607** [iamparas0/TIC-TAC-TOE#139]
Add a sign up and log in page before start playing the game. It will be more standard and better for user interface. After signing up or logging in , the user can play the game .Please assign this task to me, I will do it totally.

**Comment by iamparas0** [comment]
> Add a sign up and log in page before start playing the game. It will be more standard and better for user interface. After signing up or logging in , the user can play the game .Please assign this task to me, I will do it totally.

go for it and also add " play as a guest " . please put a short video before pr so i can review.

**Comment by sayanp607** [comment]
Thank you @iamparas0 , will do it as soon as possible.

**Comment by sayanp607** [comment]
Hello, @iamparas0 , if you don't mind , can you please help me by telling the code which i have to run in the vs code terminal to run the project because I tried "npm start" , "npm run dev" after entering TIC-TAC-TOE, but nothing worked.

**Comment by iamparas0** [comment]
> Hello, @iamparas0 , if you don't mind , can you please help me by telling the code which i have to run in the vs code terminal to run the project because I tried "npm start" , "npm run dev" after entering TIC-TAC-TOE, but nothing worked.

Please go through readme I have updated the command

**Comment by rudrapratap63** [comment]
Hello @iamparas0 ,
Could you please assign this issue to me? It was assigned to @sayanp607 three days ago, but there hasn't been any progress since then. I'd be happy to take it on and work towards resolving it.

**Comment by sayanp607** [comment]
Yeah I will submit the code tonight surely, I started working on it @iamparas0 , by the way thanks for your concern @rudrapratap63

**Comment by rudrapratap63** [comment]
Thanks for the update, @sayanp607 .

**Comment by sayanp607** [comment]
@iamparas0 brother, my sign up, login and play as a guest code is completed, but there is appearing some jsx fragment error and handlecellclick error , I think someone has also issued you about these errors, please let me know when these will be solved, then I will merge my code and make a PR.

**Comment by iamparas0** [comment]
> @iamparas0 brother, my sign up, login and play as a guest code is completed, but there is appearing some jsx fragment error and handlecellclick error , I think someone has also issued you about these errors, please let me know when these will be solved, then I will merge my code and make a PR.

I have fixed the error please update your repository

**Comment by sayanp607** [comment]
> > @iamparas0 brother, my sign up, login and play as a guest code is completed, but there is appearing some jsx fragment error and handlecellclick error , I think someone has also issued you about these errors, please let me know when these will be solved, then I will merge my code and make a PR.
> 
> I have fixed the error please update your repository

Yes, I forked your updated repository to add my sign up, login pages but it's still showing error [ Unexpected token (627:2) ]
before I put my code .
